### ISSUE TITLE
[BUG] <title>Adding Custom Tracking Script

### ISSUE THREAD

**Issue by CyberEightyFive** [Lissy93/dashy#1738]
### Environment

Self-Hosted (Docker)

### System

 Ubuntu 22.04.5 LTS

### Describe the problem

Hello,
I am looking to add a script (tracking code) 
which in the following structure:
<script type="text/javascript">
CODE
</script>

i have tried both to
1.add in the index.html within the public folder of the deployment - after <head> and before </head>.
2.within an "embed" widget of an html / script option.

both are not working. any idea ?

Thanks

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
